### ISSUE TITLE
Timeout arg?

### ISSUE THREAD

**Issue by abelsonlive** [pudo/thready#1]
Hey Friedrich, 

I've been using `thready` a lot.  No big surprise since I basically `import pudo` everything I'm writing python.

Occasionally when using `thready`, I get a timeout error that looks something like this:

```
ERROR:thready:timed out
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thready.py", line 13, in queue_consumer
    func(item)
  File "/usr/local/lib/python2.7/dist-packages/particle/promopages/promopages.py", line 114, in scrape_promo_page
    b.get(promo_url)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 176, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 162, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 349, in execute
    return self._request(url, method=command_info[0], data=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 410, in _request
    resp = opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
```

This is weird, because it doesn't seem like there's any point where you define a timeout in the source. Any thoughts?

I'm also wondering if there is some easy way we could add a max_timeout arg to `thready`?

**Comment by tlevine** [comment]
I suppose it's worth documenting this, as other people might experience the same confusion.
